<#
  ==============================================================
         COBLOS ONLINE - Domain Tunnel One-Time Setup           
      Setup Cloudflare Named Tunnel for permanent domain URL    
  ==============================================================

  Run this ONCE to setup your Cloudflare tunnel with your domain.
  After this, use tunnel_domain.ps1 to start the tunnel.
  
  Requirements:
  - Cloudflare account (free)
  - Domain must be on Cloudflare DNS
#>

$PROJECT_ROOT = Split-Path -Parent $MyInvocation.MyCommand.Definition
$CLOUDFLARED  = Join-Path $PROJECT_ROOT "cloudflared.exe"
$TUNNEL_NAME  = "coblos-online"
$DOMAIN       = "pilkasis.deckonecode.my.id"
$CONFIG_DIR   = Join-Path $env:USERPROFILE ".cloudflared"

# Find cloudflared
if (Test-Path $CLOUDFLARED) {
    $cfPath = $CLOUDFLARED
} elseif (Get-Command "cloudflared" -ErrorAction SilentlyContinue) {
    $cfPath = "cloudflared"
} else {
    Write-Host "  [ERR] cloudflared not found! Run tunnel_public.ps1 first to auto-download." -ForegroundColor Red
    exit 1
}

function Write-Step {
    param([string]$Message, [string]$Color = "Yellow")
    Write-Host "  -> $Message" -ForegroundColor $Color
}

function Write-Success {
    param([string]$Message)
    Write-Host "  [OK] $Message" -ForegroundColor Green
}

Write-Host ""
Write-Host "  ==========================================================" -ForegroundColor Cyan
Write-Host "        COBLOS ONLINE - Domain Tunnel Setup                 " -ForegroundColor Cyan
Write-Host "        Domain: $DOMAIN                                     " -ForegroundColor Cyan
Write-Host "  ==========================================================" -ForegroundColor Cyan
Write-Host ""

# ==================== STEP 1: Login to Cloudflare ====================
Write-Step "Step 1: Login ke Cloudflare Account..." "Green"
Write-Host "         Browser akan terbuka untuk login. Pilih domain/zone yang sesuai." -ForegroundColor Gray
Write-Host ""

# Check if already logged in
$certPath = Join-Path $CONFIG_DIR "cert.pem"
if (Test-Path $certPath) {
    Write-Success "Sudah login ke Cloudflare (cert.pem ditemukan)"
    $answer = Read-Host "         Login ulang? (y/N)"
    if ($answer -eq "y" -or $answer -eq "Y") {
        & $cfPath tunnel login
    }
} else {
    & $cfPath tunnel login
}

if (-not (Test-Path $certPath)) {
    Write-Host "  [ERR] Login gagal. Pastikan Anda memilih zone yang benar di browser." -ForegroundColor Red
    exit 1
}
Write-Success "Login berhasil!"

# ==================== STEP 2: Create Named Tunnel ====================
Write-Host ""
Write-Step "Step 2: Membuat Named Tunnel '$TUNNEL_NAME'..." "Green"

# Check if tunnel already exists
$tunnelList = & $cfPath tunnel list --output json 2>&1
$existingTunnel = $null
try {
    $tunnels = $tunnelList | ConvertFrom-Json
    $existingTunnel = $tunnels | Where-Object { $_.name -eq $TUNNEL_NAME }
} catch {}

if ($existingTunnel) {
    Write-Success "Tunnel '$TUNNEL_NAME' sudah ada (ID: $($existingTunnel.id))"
    $tunnelId = $existingTunnel.id
} else {
    $createOutput = & $cfPath tunnel create $TUNNEL_NAME 2>&1
    Write-Host "         $createOutput" -ForegroundColor Gray
    
    # Get tunnel ID
    $tunnelList = & $cfPath tunnel list --output json 2>&1
    $tunnels = $tunnelList | ConvertFrom-Json
    $existingTunnel = $tunnels | Where-Object { $_.name -eq $TUNNEL_NAME }
    
    if ($existingTunnel) {
        $tunnelId = $existingTunnel.id
        Write-Success "Tunnel dibuat! ID: $tunnelId"
    } else {
        Write-Host "  [ERR] Gagal membuat tunnel." -ForegroundColor Red
        exit 1
    }
}

# ==================== STEP 3: Create Config File ====================
Write-Host ""
Write-Step "Step 3: Membuat config file..." "Green"

$configPath = Join-Path $CONFIG_DIR "config.yml"
$credentialsFile = Join-Path $CONFIG_DIR "$tunnelId.json"

$configContent = @(
    "# Coblos Online - Cloudflare Tunnel Config",
    "# Auto-generated by setup_domain_tunnel.ps1",
    "",
    "tunnel: $tunnelId",
    "credentials-file: $credentialsFile",
    "",
    "ingress:",
    "  - hostname: $DOMAIN",
    "    service: http://localhost:8000",
    "    originRequest:",
    "      noTLSVerify: true",
    "  - service: http_status:404"
) -join [Environment]::NewLine

$configContent | Set-Content -Path $configPath -Encoding UTF8
Write-Success "Config file dibuat: $configPath"

# ==================== STEP 4: Route DNS ====================
Write-Host ""
Write-Step "Step 4: Routing DNS $DOMAIN ke tunnel..." "Green"

$dnsOutput = & $cfPath tunnel route dns $TUNNEL_NAME $DOMAIN 2>&1
Write-Host "         $dnsOutput" -ForegroundColor Gray

# Check if it was successful or already exists
if ($dnsOutput -match "already exists|Added CNAME|successfully") {
    Write-Success "DNS route berhasil!"
} else {
    Write-Host "  [!] DNS routing mungkin gagal. Pastikan domain ada di Cloudflare." -ForegroundColor Yellow
    Write-Host "         Anda bisa manual tambahkan CNAME record:" -ForegroundColor Gray
    Write-Host "         $DOMAIN  ->  $tunnelId.cfargotunnel.com" -ForegroundColor White
}

# ==================== STEP 5: Save tunnel info ====================
Write-Host ""
Write-Step "Step 5: Menyimpan informasi tunnel..." "Green"

$tunnelInfoPath = Join-Path $PROJECT_ROOT ".tunnel-config.json"
@{
    tunnel_name = $TUNNEL_NAME
    tunnel_id   = $tunnelId
    domain      = $DOMAIN
    config_path = $configPath
    credentials = $credentialsFile
    created_at  = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
} | ConvertTo-Json | Set-Content -Path $tunnelInfoPath -Encoding UTF8

Write-Success "Info tunnel disimpan ke .tunnel-config.json"

# ==================== DONE ====================
Write-Host ""
Write-Host "  ==========================================================" -ForegroundColor Green
Write-Host "                    SETUP SELESAI!                          " -ForegroundColor Green
Write-Host "  ==========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  [Informasi Tunnel]:" -ForegroundColor Cyan
Write-Host "  ------------------------------------------------------------" -ForegroundColor DarkGray
Write-Host "    Tunnel Name : $TUNNEL_NAME" -ForegroundColor DarkGray
Write-Host "    Tunnel ID   : $tunnelId" -ForegroundColor DarkGray
Write-Host "    Domain      : https://$DOMAIN" -ForegroundColor White
Write-Host "    Config      : $configPath" -ForegroundColor DarkGray
Write-Host "  ------------------------------------------------------------" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  [Langkah selanjutnya]:" -ForegroundColor Yellow
Write-Host "     Jalankan: .\tunnel_domain.bat" -ForegroundColor White
Write-Host "     atau:     .\tunnel_domain.ps1" -ForegroundColor White
Write-Host ""

pause
