<#
  ==============================================================
         COBLOS ONLINE - Domain Tunnel Runner                   
      Run tunnel with your domain (permanent URL)               
      Domain: osisvote.codeteacher.full.diskon.cloud            
  ==============================================================

  This script:
  1. Builds the React frontend
  2. Copies build files to Laravel's public directory
  3. Starts Laravel backend
  4. Runs Cloudflare named tunnel with your domain

  Prerequisites:
  - Run setup_domain_tunnel.ps1 ONCE first
  - MySQL running with 'coblos_online' database
#>

# ======================== CONFIG ========================
$BACKEND_PORT  = 8000
$PROJECT_ROOT  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$BACKEND_DIR   = Join-Path $PROJECT_ROOT "backend"
$FRONTEND_DIR  = Join-Path $PROJECT_ROOT "frontend"
$LOG_DIR       = Join-Path $PROJECT_ROOT ".tunnel-logs"
$CLOUDFLARED   = Join-Path $PROJECT_ROOT "cloudflared.exe"
$TUNNEL_CONFIG = Join-Path $PROJECT_ROOT ".tunnel-config.json"
$DOMAIN        = "pilkasis.deckonecode.my.id"
# ========================================================

# Create log directory
if (-not (Test-Path $LOG_DIR)) {
    New-Item -ItemType Directory -Path $LOG_DIR -Force | Out-Null
}

function Write-Banner {
    Write-Host ""
    Write-Host "  ==========================================================" -ForegroundColor Cyan
    Write-Host "        COBLOS ONLINE - Domain Tunnel Runner                " -ForegroundColor Cyan
    Write-Host "        https://$DOMAIN                                     " -ForegroundColor Cyan
    Write-Host "  ==========================================================" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Step {
    param([string]$Message, [string]$Color = "Yellow")
    Write-Host "  -> $Message" -ForegroundColor $Color
}

function Write-Success {
    param([string]$Message)
    Write-Host "  [OK] $Message" -ForegroundColor Green
}

function Write-Error-Custom {
    param([string]$Message)
    Write-Host "  [ERR] $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "  [INFO] $Message" -ForegroundColor DarkCyan
}

function Get-CloudflaredPath {
    if (Test-Path $CLOUDFLARED) { return $CLOUDFLARED }
    if (Get-Command "cloudflared" -ErrorAction SilentlyContinue) { return "cloudflared" }
    return $null
}

function Stop-AllProcesses {
    Write-Host ""
    Write-Step "Shutting down all processes..." "Red"
    Get-Process -Name "cloudflared" -ErrorAction SilentlyContinue | Stop-Process -Force
    $phpProcs = Get-NetTCPConnection -LocalPort $BACKEND_PORT -ErrorAction SilentlyContinue |
                Select-Object -ExpandProperty OwningProcess -Unique
    foreach ($procId in $phpProcs) {
        Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
    }
    Write-Success "All processes stopped."
}

# ======================== MAIN ========================

Write-Banner

# Check prerequisites
Write-Step "Checking prerequisites..."

$cfPath = Get-CloudflaredPath
if (-not $cfPath) {
    Write-Error-Custom "cloudflared not found! Run tunnel_public.ps1 first to auto-download."
    exit 1
}

if (-not (Test-Path $TUNNEL_CONFIG)) {
    Write-Error-Custom "Tunnel belum di-setup!"
    Write-Host "         Jalankan dulu: " -NoNewline -ForegroundColor Gray
    Write-Host ".\setup_domain_tunnel.ps1" -ForegroundColor White
    exit 1
}

$tunnelInfo = Get-Content $TUNNEL_CONFIG -Raw | ConvertFrom-Json
Write-Success "Tunnel config ditemukan: $($tunnelInfo.tunnel_name) (ID: $($tunnelInfo.tunnel_id))"

# Save original backend .env
$backendEnvPath = Join-Path $BACKEND_DIR ".env"
$backendEnvOriginal = Get-Content $backendEnvPath -Raw

try {
    # ==================== STEP 1: Build Frontend ====================
    Write-Host ""
    Write-Step "Building React Frontend..." "Green"

    # Create .env for production build with the domain API URL
    $frontendEnvPath = Join-Path $FRONTEND_DIR ".env"
    $frontendEnvOriginal = Get-Content $frontendEnvPath -Raw

    # Set API URL to the domain itself (since backend serves everything)
    @"
# Auto-generated by tunnel_domain.ps1
VITE_API_URL=https://$DOMAIN/api
"@ | Set-Content -Path $frontendEnvPath -Encoding UTF8

    # Run build
    $buildProcess = Start-Process -FilePath "cmd.exe" `
        -ArgumentList "/c", "npm run build" `
        -WorkingDirectory $FRONTEND_DIR `
        -Wait -PassThru -WindowStyle Hidden `
        -RedirectStandardOutput (Join-Path $LOG_DIR "frontend-build.log") `
        -RedirectStandardError (Join-Path $LOG_DIR "frontend-build-error.log")

    if ($buildProcess.ExitCode -ne 0) {
        $buildError = Get-Content (Join-Path $LOG_DIR "frontend-build-error.log") -Raw
        Write-Error-Custom "Frontend build failed!"
        Write-Host "         $buildError" -ForegroundColor Red
        exit 1
    }

    Write-Success "Frontend built successfully!"

    # Restore original frontend .env
    Set-Content -Path $frontendEnvPath -Value $frontendEnvOriginal -Encoding UTF8 -NoNewline

    # ==================== STEP 2: Copy Build to Laravel ====================
    Write-Host ""
    Write-Step "Copying frontend build to Laravel public/..." "Green"

    $distDir = Join-Path $FRONTEND_DIR "dist"
    $publicDir = Join-Path $BACKEND_DIR "public"

    if (-not (Test-Path $distDir)) {
        Write-Error-Custom "Build directory not found: $distDir"
        exit 1
    }

    # Create a subfolder marker to know what we added (for cleanup)
    $spaMarker = Join-Path $publicDir ".spa-deployed"

    # Copy all build assets to Laravel public
    # But first, backup the existing index.php and .htaccess
    $indexPhpBackup = Join-Path $LOG_DIR "index.php.bak"
    $htaccessBackup = Join-Path $LOG_DIR ".htaccess.bak"
    Copy-Item (Join-Path $publicDir "index.php") $indexPhpBackup -Force
    Copy-Item (Join-Path $publicDir ".htaccess") $htaccessBackup -Force

    # Copy dist contents (assets folder, index.html, etc.)
    Get-ChildItem $distDir | ForEach-Object {
        $destPath = Join-Path $publicDir $_.Name
        if ($_.PSIsContainer) {
            Copy-Item $_.FullName $destPath -Recurse -Force
        } else {
            # Don't overwrite Laravel's index.php with React's index.html
            if ($_.Name -ne "index.html") {
                Copy-Item $_.FullName $destPath -Force
            }
        }
    }

    # Rename React's index.html to spa.html (we'll serve it via Laravel route)
    $reactIndexSrc = Join-Path $distDir "index.html"
    $reactIndexDst = Join-Path $publicDir "spa.html"
    Copy-Item $reactIndexSrc $reactIndexDst -Force

    # Create marker
    "deployed" | Set-Content -Path $spaMarker -Encoding UTF8

    Write-Success "Frontend assets copied to Laravel public/"

    # ==================== STEP 3: Configure Backend ====================
    Write-Host ""
    Write-Step "Configuring Backend for domain tunnel..." "Yellow"

    # Update backend .env
    $backendEnvContent = $backendEnvOriginal.TrimEnd()
    # Remove existing overrides
    $backendEnvContent = $backendEnvContent -replace "(?m)^# Tunnel Override.*\r?\n?", ""
    $backendEnvContent = $backendEnvContent -replace "(?m)^CORS_ALLOWED_ORIGINS=.*\r?\n?", ""
    $backendEnvContent = $backendEnvContent -replace "(?m)^SANCTUM_STATEFUL_DOMAINS=.*\r?\n?", ""
    $backendEnvContent = $backendEnvContent -replace "(?m)^SESSION_DOMAIN=.*\r?\n?", ""
    $backendEnvContent = $backendEnvContent -replace "(?m)^APP_URL=.*", "APP_URL=https://$DOMAIN"
    $backendEnvContent = $backendEnvContent.TrimEnd()

    $backendEnvContent += @"

# Tunnel Override
CORS_ALLOWED_ORIGINS=https://$DOMAIN,http://localhost:5173,http://127.0.0.1:5173
SANCTUM_STATEFUL_DOMAINS=$DOMAIN,localhost,127.0.0.1
SESSION_DOMAIN=.$DOMAIN
"@

    Set-Content -Path $backendEnvPath -Value $backendEnvContent -Encoding UTF8 -NoNewline

    # Clear config cache
    Start-Process -FilePath "php" -ArgumentList "artisan", "config:clear" `
        -WorkingDirectory $BACKEND_DIR -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue

    Write-Success "Backend .env updated for domain"

    # ==================== STEP 4: Start Backend ====================
    Write-Host ""
    Write-Step "Starting Laravel Backend on port $BACKEND_PORT..." "Green"

    $backendLog = Join-Path $LOG_DIR "backend-domain.log"
    $backendProc = Start-Process -FilePath "php" `
        -ArgumentList "artisan", "serve", "--host=127.0.0.1", "--port=$BACKEND_PORT" `
        -WorkingDirectory $BACKEND_DIR `
        -RedirectStandardOutput $backendLog `
        -RedirectStandardError (Join-Path $LOG_DIR "backend-domain-error.log") `
        -PassThru -WindowStyle Hidden

    Start-Sleep -Seconds 3

    try {
        $null = Invoke-WebRequest -Uri "http://127.0.0.1:$BACKEND_PORT/up" -UseBasicParsing -TimeoutSec 5
        Write-Success "Backend running on http://127.0.0.1:$BACKEND_PORT"
    } catch {
        Write-Error-Custom "Backend failed to start!"
        Write-Info "Make sure MySQL is running and database 'coblos_online' exists."
        exit 1
    }

    # ==================== STEP 5: Start Named Tunnel ====================
    Write-Host ""
    Write-Step "Starting Cloudflare Named Tunnel..." "Magenta"

    $tunnelLog = Join-Path $LOG_DIR "tunnel-domain.log"
    if (Test-Path $tunnelLog) { 
        Remove-Item $tunnelLog -Force -ErrorAction SilentlyContinue 
        if (Test-Path $tunnelLog) { Clear-Content $tunnelLog -Force -ErrorAction SilentlyContinue }
    }

    $tunnelProc = Start-Process -FilePath $cfPath `
        -ArgumentList "tunnel", "run", $tunnelInfo.tunnel_name `
        -RedirectStandardOutput (Join-Path $LOG_DIR "tunnel-domain-stdout.log") `
        -RedirectStandardError $tunnelLog `
        -PassThru -WindowStyle Hidden

    Start-Sleep -Seconds 5

    # Check if tunnel is running
    if ($tunnelProc.HasExited) {
        $tunnelError = Get-Content $tunnelLog -Raw
        Write-Error-Custom "Tunnel failed to start!"
        Write-Host "         $tunnelError" -ForegroundColor Red
        exit 1
    }

    Write-Success "Cloudflare tunnel running!"

    # ==================== ALL DONE ====================
    Write-Host ""
    Write-Host "  ============================================================" -ForegroundColor Green
    Write-Host "               COBLOS ONLINE IS LIVE!                       " -ForegroundColor Green
    Write-Host "  ============================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "  [PUBLIC URL - Share this for voting!]:" -ForegroundColor Cyan
    Write-Host "  ------------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "    https://$DOMAIN" -ForegroundColor White
    Write-Host "  ------------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "  [Endpoints]:" -ForegroundColor Cyan
    Write-Host "     Home     : https://$DOMAIN" -ForegroundColor White
    Write-Host "     Admin    : https://$DOMAIN/admin/login" -ForegroundColor White
    Write-Host "     API      : https://$DOMAIN/api" -ForegroundColor White
    Write-Host ""
    Write-Host "    Local      : http://127.0.0.1:$BACKEND_PORT" -ForegroundColor DarkGray
    Write-Host "    Logs       : $LOG_DIR" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "  [*] URL ini PERMANEN - tidak berubah setiap restart!" -ForegroundColor Green
    Write-Host "  [!] Tekan Ctrl+C untuk menghentikan semua service." -ForegroundColor Yellow
    Write-Host ""

    # Save URL info
    $urlInfoPath = Join-Path $PROJECT_ROOT "TUNNEL_URLS.txt"
    @"
====================================
COBLOS ONLINE - Domain Tunnel
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
====================================

PUBLIC URL (permanent!):
  https://$DOMAIN

Admin Panel:
  https://$DOMAIN/admin/login

API:
  https://$DOMAIN/api

LOCAL:
  http://127.0.0.1:$BACKEND_PORT

====================================
"@ | Set-Content -Path $urlInfoPath -Encoding UTF8
    Write-Info "URLs saved to TUNNEL_URLS.txt"
    Write-Host ""

    # Keep running with health checks
    Write-Host "  Press Ctrl+C to stop all services..." -ForegroundColor DarkGray
    Write-Host ""

    while ($true) {
        Start-Sleep -Seconds 10

        # Health check backend
        $backendAlive = $false
        try {
            $null = Invoke-WebRequest -Uri "http://127.0.0.1:$BACKEND_PORT/up" -UseBasicParsing -TimeoutSec 3
            $backendAlive = $true
        } catch {}

        if (-not $backendAlive) {
            Write-Step "Backend down! Auto-restarting..." "Red"
            $backendProc = Start-Process -FilePath "php" `
                -ArgumentList "artisan", "serve", "--host=127.0.0.1", "--port=$BACKEND_PORT" `
                -WorkingDirectory $BACKEND_DIR `
                -RedirectStandardOutput (Join-Path $LOG_DIR "backend-auto-restart.log") `
                -RedirectStandardError (Join-Path $LOG_DIR "backend-auto-restart-error.log") `
                -PassThru -WindowStyle Hidden
            Write-Success "Backend restarted!"
        }

        # Check tunnel
        if ($tunnelProc.HasExited) {
            Write-Step "Tunnel died! Auto-restarting..." "Red"
            $tunnelProc = Start-Process -FilePath $cfPath `
                -ArgumentList "tunnel", "run", $tunnelInfo.tunnel_name `
                -RedirectStandardOutput (Join-Path $LOG_DIR "tunnel-domain-restart-stdout.log") `
                -RedirectStandardError (Join-Path $LOG_DIR "tunnel-domain-restart.log") `
                -PassThru -WindowStyle Hidden
            Write-Success "Tunnel restarted!"
        }
    }
} finally {
    # Cleanup
    Write-Host ""
    Write-Step "Cleaning up..." "Yellow"

    # Restore original backend .env
    Set-Content -Path $backendEnvPath -Value $backendEnvOriginal -Encoding UTF8 -NoNewline

    # Clear config cache
    Start-Process -FilePath "php" -ArgumentList "artisan", "config:clear" `
        -WorkingDirectory $BACKEND_DIR -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue

    # Clean up SPA files from public directory
    $publicDir = Join-Path $BACKEND_DIR "public"
    $spaMarker = Join-Path $publicDir ".spa-deployed"
    if (Test-Path $spaMarker) {
        # Remove SPA assets
        $assetsDir = Join-Path $publicDir "assets"
        if (Test-Path $assetsDir) { Remove-Item $assetsDir -Recurse -Force }
        $spaHtml = Join-Path $publicDir "spa.html"
        if (Test-Path $spaHtml) { Remove-Item $spaHtml -Force }
        $viteManifest = Join-Path $publicDir ".vite"
        if (Test-Path $viteManifest) { Remove-Item $viteManifest -Recurse -Force }
        Remove-Item $spaMarker -Force

        # Restore original index.php and .htaccess if backed up
        $indexPhpBackup = Join-Path $LOG_DIR "index.php.bak"
        $htaccessBackup = Join-Path $LOG_DIR ".htaccess.bak"
        if (Test-Path $indexPhpBackup) {
            Copy-Item $indexPhpBackup (Join-Path $publicDir "index.php") -Force
        }
        if (Test-Path $htaccessBackup) {
            Copy-Item $htaccessBackup (Join-Path $publicDir ".htaccess") -Force
        }
    }

    Stop-AllProcesses
    Write-Success "Cleanup complete. Original files restored."
    Write-Host ""
}
